-- MySQL Script generated by MySQL Workbench
-- 10/25/15 00:57:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sbauth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sbauth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sbauth` DEFAULT CHARACTER SET latin1 ;
USE `sbauth` ;

-- -----------------------------------------------------
-- Table `sbauth`.`secrets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbauth`.`secrets` (
  `SECRETID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `USERID` INT(11) NOT NULL COMMENT '',
  `Challenge` VARCHAR(256) NOT NULL COMMENT '',
  `EXPIRED` SMALLINT(6) NOT NULL COMMENT '',
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`SECRETID`)  COMMENT '',
  UNIQUE INDEX `SECRETID` (`SECRETID` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sbauth`.`seeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbauth`.`seeds` (
  `USERID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `URLSEED` BIGINT(20) NOT NULL COMMENT '',
  `UNMSEED` BIGINT(20) NOT NULL COMMENT '',
  `EXPIRED` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`USERID`)  COMMENT '',
  UNIQUE INDEX `SEEDID_3` (`USERID` ASC)  COMMENT '',
  INDEX `SEEDID` (`USERID` ASC)  COMMENT '',
  INDEX `SEEDID_2` (`USERID` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1015
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sbauth`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbauth`.`tokens` (
  `tokensID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `URLTOKEN` VARCHAR(20) NOT NULL COMMENT '',
  `UNMTOKEN` VARCHAR(20) NOT NULL COMMENT '',
  `SEQUENCE` SMALLINT(6) NOT NULL COMMENT '',
  `USERID` INT(11) NOT NULL COMMENT '',
  `EXPIRED` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`tokensID`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 206
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
